version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: aprendendo_kafka
    networks:
        - save_service
    ports:
      - 3306:3306
  app:
    build: .
    volumes:
      - .:/usr/app
    command: yarn start
    ports:
      - 3334:3334
    networks:
      - net
      - save_service
    depends_on:
      - db

      
networks:
  net:
    external: true

  save_service:
    external: false
    driver: bridge

    